<a href="https://colab.research.google.com/github/9-coding/DeepLearningZeroToAll/blob/main/Lab06_SoftmaxClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# Lab-06 Softmax Classifier
# Logistic Regression 참조하여 구성

import tensorflow as tf
import numpy as np

x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

x_data = np.asarray(x_data, dtype = np.float32)
y_data = np.asarray(y_data, dtype = np.float32)

dataset = tf.data.Dataset.from_tensor_slices((x_data, y_data)).batch(len(x_data))
W = tf.Variable(tf.random.normal([4,3], name='weight'))
b = tf.Variable(tf.random.normal([3]),name = 'bias')
variable = [W, b]

# 원소의 자료구조 반환
dataset.element_spec

def softmax_fn (features):
    hypothesis = tf.nn.softmax(tf.matmul(features,W)+b)
    return hypothesis

def loss_fn (features, labels):
    hypothesis = tf.nn.softmax(tf.matmul(features,W)+b)
    cost = tf.reduce_mean(-tf.reduce_sum(y_data * tf.math.log(hypothesis), axis =1))
    return cost

def grad (hypothesis, features, labels):
    with tf.GradientTape() as tape:
        loss_value = loss_fn(features, labels)
    return tape.gradient(loss_value, [W, b])

optimizer = tf.keras.optimizers.SGD(learning_rate = 0.01)

EPOCHS = 3000

for step in range(EPOCHS + 1):
    for features, labels in iter(dataset):
        hypothesis = softmax_fn(features)
        grads = grad(hypothesis, features, labels)
        optimizer.apply_gradients(grads_and_vars = zip(grads, [W, b]))
        if step % 300 == 0:
                print("iter: {}, Loss: {:.4f}".format(step, loss_fn(features, labels)))

a = x_data
a = softmax_fn (a)
print(hypothesis) # softmax 함수를 통과시킨 x_data

# argmax 가장 큰 값의 index를 찾아줌

print(tf.argmax(a,1)) # 가설을 통한 예측값
print(tf.argmax(y_data,1)) # 실제 값

iter: 0, Loss: 6.4214
iter: 300, Loss: 0.4962
iter: 600, Loss: 0.4649
iter: 900, Loss: 0.4482
iter: 1200, Loss: 0.4339
iter: 1500, Loss: 0.4211
iter: 1800, Loss: 0.4093
iter: 2100, Loss: 0.3984
iter: 2400, Loss: 0.3883
iter: 2700, Loss: 0.3788
iter: 3000, Loss: 0.3698
tf.Tensor(
[[3.6314048e-03 2.8929424e-02 9.6743912e-01]
 [8.2057863e-03 1.4974450e-01 8.4204972e-01]
 [6.6882739e-04 3.6115184e-01 6.3817924e-01]
 [6.1523635e-04 6.8219411e-01 3.1719074e-01]
 [5.2363032e-01 4.4592294e-01 3.0446663e-02]
 [2.6981068e-01 7.2880918e-01 1.3801689e-03]
 [6.1499602e-01 3.8297424e-01 2.0296504e-03]
 [7.3189980e-01 2.6783043e-01 2.6977173e-04]], shape=(8, 3), dtype=float32)
tf.Tensor([2 2 2 1 0 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)


### 데이터 세팅
- 3개의 클래스 분류할때 0,1,2 를 각각 [1,0,0], [0,1,0], [0,0,1]로 one-hot-encoding
- y의 개수 = 클래스 개수 = label개수
<br>dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(len(x_train))<br>
- tf.data.Dataset 파이프라인을 이용하여 값을 입력
- from_tensor_slices 클래스 매서드를 사용하면 리스트, 넘파이, 텐서플로우 자료형에서 데이터셋을 만들 수 있음


### <br>def softmax_fn (features):
- 소프트맥스 함수 설정
- hypothesis = tf.nn.softmax(tf.matmul(features,W)+b)

### <br>def loss_fn(features, labels):
- 비용 반환 함수.

### <br> def grad(hypothesis, features, labels):
- 기울기를 구하며 변수의 정보들을 tape에 기록.

### <br> 학습
optimizer.apply_gradients(grads_and_vars=zip(grads, [W,b]))
-  epoch를 돌면서 optimizer를 통해 지속적으로 최적값 update. -> 최적값을 찾아감.